markdown: kramdown
kramdown:
    auto_ids: true
    entity_output: symbolic
highlighter: null

url: http://beets.io
permalink: /blog/:title.html

defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: main
            section: blog
